---
- name: Pull Docker Image from Docker Hub and start the container
  hosts: localhost
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "kartikeyblaze/scientific-calculator:latest"
        source: pull

    - name: Remove existing container if it exists
      docker_container:
        name: "calculator"
        state: absent
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator kartikeyblaze/scientific-calculator:latest
